NAME: "VolcEngineAPI"
VERSION: "v0.0.1"
DESC: "接入火山引擎LLM"
META:
  official: "https://www.volcengine.com/"
  configuration: "https://console.volcengine.com/ark"
  tips: "支持豆包大模型"
PARAMETERS:
  - name: "VOLCENGINE_API_KEY"
    description: "火山引擎 API Key"
    type: "string"
    required: False
    default: "5e406c6c-60b1-4842-be32-9b9964068792"
  - name: "VOLCENGINE_MODEL_NAME"
    description: "模型名称"
    type: "string"
    required: False
    default: "doubao-seed-1-8-251228"
